### PR TITLE
prevent dragging images out of the thumb carousel

### LINKED ISSUE #41: quotebox images can be clickdragged
It's probably a good idea to give the images an `dragStart={e => e.preventDefault()}` to prevent this from happening.

### PR DESCRIPTION
**Pull request by Pomax**
fixes #41 

This prevents drags when a user clicks a thumb carousel image while also moving the mouse.

### CODE REVIEW

**Comment by alanmoo** [comment]
This works, but I'm curious about the use case. Is there a time when being able to do the browser native behavior is a concern?

**Comment by Pomax** [comment]
this happened almost every time I was trying to click through the carousel, so: every.

**Comment by alanmoo** [comment]
Lol ok. Out of curiosity, what kind of mousing device do you use?

**Comment by Pomax** [comment]
logitech G500s gaming mouse set to a high dpi value for design/illustration/photo work.

**Comment by alanmoo** [comment]
Ah, the sensitivity means it's not likely that you click and don't move the mouse?

**Comment by Pomax** [comment]
exactly, it can see 1px travel during a click quite easily.

**Pull request merged**
