### PR TITLE
Adding theme switcher to demo

### LINKED ISSUE #14: create bootstrap switcher for demo page
Add a way to preview the demo page with the following:

1. mofo-bootstrap added
2. bootstrap 3 added
3. no additional CSS added

### PR DESCRIPTION
**Pull request by gvn**
closes #14

### CODE REVIEW

**Comment by gvn** [comment]
@flukeout Would you be comfortable reviewing this?

**Comment by flukeout** [comment]
Looking into it!

**Comment by flukeout** [comment]
Took a look at it, seems fine to me!
It also works as expected, switching between various themes.

Is this meant to illustrate what happens when we apply mofo-ui to a property that has different Boostrap instances already running?

**Comment by gvn** [comment]
Yep, exactly! As you can see we need to change some class names because they are clashing with Bootstrap 3. This switcher should help us fix and avoid that happening.

**Pull request merged**
