### PR TITLE
Add mofo-standards badge

### PR DESCRIPTION
**Pull request by gvn**

### CODE REVIEW

**Comment by alanmoo** [comment]
Nope, apparently I missed this one when looking at the labels

**Comment by alanmoo** [comment]
Does this project actually get deployed anywhere?

**Comment by gvn** [comment]
Yes, to `gh-pages` and npm.

**Comment by alanmoo** [comment]
So it's not exactly mofo-standards? Maybe we need a section in that repo about gh-pages (libraries) projects.

**Comment by alanmoo** [comment]
Oh nevermind, just switch gh-pages to point to `master` and this'll be all set: https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by gvn** [comment]
Hmm that requires putting compiled files on `master` in this case. That's not desirable.

We probably should add a section on libraries in `mofo-standards` though...

**Comment by alanmoo** [comment]
Why not a `preversion` script that generates the docs folder?

**Comment by gvn** [comment]
What docs folder?

**Comment by alanmoo** [comment]
A docs folder that gets used as the source of gh pages. (See above link)

**Comment by gvn** [comment]
Again, I don't want to put compiled files on master. There's a deploy task for pushing the compiled demo to gh-pages.

Regardless, this seems tangential to adding the badge. Feel free to open a follow up discussion ticket if you have alternative ideas about deployment. I'm open to having deploy run as a `postversion`.

For now, I'd like to land this patch as this repo does use a subset of `mofo-standards`.

**Comment by alanmoo** [comment]
I can open a separate issue about the gh-pages, but I still don't think this should have the badge until either 1.) this repo has specific documentation about its deploy process, or 2.) mofo-standards has documentation about how libraries with gh-pages are handled.

**Comment by gvn** [comment]
Ok cool.

**Pull request merged**
