### PR TITLE
making npm scripts x-platform compatible

### LINKED ISSUE #15: Ensure npm tasks work w. Windows
"there are some issues with getting mofo-ui to build properly on windows, it looks like the cp command that puts files in demo/css instead leads to the code writing a file called css (without extension) in the demo dir. Of course that doesn't affect the actual library in dist but it does require a bit of manual intervention for testing the code on localhost. We might want to use the mkdirp package to bootstrap the dir structure inside demo prior to the cp commands." - @Pomax

### PR DESCRIPTION
**Pull request by gvn**
closes #15

### CODE REVIEW

**Comment by gvn** [comment]
Should hopefully work on Windows now!

**Comment by Pomax** [comment]
lets me chex!

**Comment by Pomax** [comment]
R+ :100: 

and https://www.npmjs.com/package/shx might be my new favourite package (at least for a day =D)

**Comment by gvn** [comment]
`shx` is really awesome! I think we should consider standardizing on it for x-platform-enabling.

**Pull request merged**
